version: "3"

services:
  nginx:
    container_name: easy-nginx
    image: nginx:1.15-alpine
    build: ./nginx
    volumes: 
      - ./www:/mnt/www
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      # - ./etc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./runtime/logs/nginx:/tmp/logs/nginx
    ports: 
      - "80:80"
      # - "443:443"
    networks: 
      - default
  php727:
    container_name: easy-php
    image: php:7.2.7-fpm-alpine3.6
    build: ./php
    volumes:
      - ./www:/mnt/www
      - ./php/conf/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/extensions/:/usr/local/lib/php/extensions
      - ./runtime/logs/php:/tmp/logs/php
      - ./php/conf/conf.d:/usr/local/etc/php/conf.d
    ports:
      - "9000:9000"
    networks: 
      - default
  redis:
    container_name: easy-redis
    image: redis:4-alpine
    build: ./redis
    volumes:
      - ./runtime/logs/redis:/tmp/logs/redis
    ports:
      - "6379:6379"
    networks: 
      - default
  mysql:
    container_name: easy-mysql
    image: mysql:5.7
    build: ./mysql
    environment: 
      MYSQL_ROOT_PASSWORD: easy
    volumes:
      - ./runtime/logs/redis:/tmp/logs/mysql
    ports:
      - "3306:3306"
    networks: 
      - default
  mongo:
    container_name: easy-mongo
    image: mongo:3.6-jessie
    build: ./mongo
    volumes:
      - ./runtime/logs/mongo:/tmp/logs/mongo
    ports:
      - "27017:27017"
    networks: 
      - default
networks: 
  default:
    external: 
      name: easy