version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    build: ./nginx
    volumes: 
      - ./www:/mnt/www
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      # - ./etc/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./runtime/logs/nginx:/tmp/logs/nginx
    ports: 
      - "80:80"
      # - "80:8080"
      # - "8080:8080"
      - "443:443"
  php727:
      image: php:7.2.7-fpm-alpine3.6
      build: ./php
      volumes:
        - ./www:/mnt/www
        - ./php/conf/php-fpm.d:/usr/local/etc/php-fpm.d
        - ./php/extensions/:/usr/local/lib/php/extensions
        - ./runtime/logs/php:/tmp/logs/php
        - ./php/conf/conf.d:/usr/local/etc/php/conf.d
      ports:
        - "9006:9000"
  redis:
      image: redis:4-alpine
      build: ./redis
      volumes:
        - ./runtime/logs/redis:/tmp/logs/redis
      ports:
        - "63799:6379"
  mysql:
      image: mysql:5.7
      build: ./mysql
      environment: 
        MYSQL_ROOT_PASSWORD: easy
      volumes:
        - ./runtime/logs/redis:/tmp/logs/mysql
      ports:
        - "3306:3306"